server {
    listen 80;
    server_name _;

    location / {
        return 200 "ZTD Server Frontend Gateway\n";
        add_header Content-Type text/plain;
    }

    location /api/ {
        return 200 "ZTD API Gateway - Backend not connected yet\n";
        add_header Content-Type text/plain;
    }

    location /mqtt {
        proxy_pass http://ztd-mqtt:9001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

}
